import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { dataStore, Customer } from '../data/store';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Card, CardContent } from '../components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '../components/ui/dialog';
import { Label } from '../components/ui/label';
import { Badge } from '../components/ui/badge';
import { Plus, Search, UserCircle } from 'lucide-react';
import { previewNextNumber } from '../utils/numberGenerator';
import { Skeleton } from '../components/ui/skeleton';
import { usePermissionsMatrix } from '../contexts/PermissionsMatrixContext';
import { useLanguage } from '../contexts/LanguageContext';
import { AccessDenied } from '../components/AccessDenied';

export function CustomersPage() {
  const navigate = useNavigate();
  const { t } = useLanguage();
  const { hasPermission } = usePermissionsMatrix();
  const canView = hasPermission('customers', 'view');
  const canCreate = hasPermission('customers', 'create');
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [dialogOpen, setDialogOpen] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  const [newCustomer, setNewCustomer] = useState({
    name: '',
    email: '',
    phone: '',
    address: '',
    vatNumber: '',
    contactPerson: '',
  });

  // Load customers and projects on mount
  useEffect(() => {
    const loadData = async () => {
      const [customersData, projectsData] = await Promise.all([
        dataStore.getCustomers(),
        dataStore.getProjects(),
      ]);
      setCustomers(customersData);
      setProjects(projectsData);
      setIsLoading(false);
    };
    loadData();
  }, []);

  // Generate customer code when dialog opens
  useEffect(() => {
    if (dialogOpen) {
      previewNextNumber('customer').then(setAutoGeneratedCode);
    }
  }, [dialogOpen]);

  const filteredCustomers = customers.filter(customer =>
    customer.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
    customer.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
    (customer.code && customer.code.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  const handleCreateCustomer = async () => {
    if (!newCustomer.name || !newCustomer.email || !newCustomer.phone) {
      alert(t('customers.requiredFields'));
      return;
    }

    await dataStore.addCustomer(newCustomer);
    
    // Reload customers from database
    const customersData = await dataStore.getCustomers();
    setCustomers(customersData);
    
    setDialogOpen(false);
    setNewCustomer({
      name: '',
      email: '',
      phone: '',
      address: '',
      vatNumber: '',
      contactPerson: '',
    });
  };

  const getInitials = (name: string) => {
    return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2);
  };

  if (!canView) {
    return <AccessDenied message={t('common.accessDenied')} />;
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold">{t('customers.title')}</h1>
          <p className="text-gray-500 mt-1">{t('customers.subtitle')}</p>
        </div>

        <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
          {canCreate && (
          <DialogTrigger asChild>
            <Button className="bg-[#7A1516] hover:bg-[#5A1012]">
              <Plus className="w-4 h-4 mr-2" />
              {t('customers.addCustomer')}
            </Button>
          </DialogTrigger>
          )}
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>{t('customers.addNewCustomer')}</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              {/* Customer Code - Auto-generated */}
              <div className="space-y-2">
                <Label>{t('customers.customerCode')}</Label>
                <div className="bg-gray-100 rounded-lg p-3 border border-gray-200">
                  <Badge className="bg-[#7A1516] text-white px-3 py-1 text-sm">
                    {autoGeneratedCode}
                  </Badge>
                </div>
                <p className="text-sm text-gray-500">Auto-generated</p>
              </div>

              {/* Two Column Layout */}
              <div className="grid grid-cols-2 gap-4">
                {/* Left Column */}
                <div className="space-y-4">
                  <div className="space-y-2">
                    <Label>
                      {t('customers.customerName')} <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      value={newCustomer.name}
                      onChange={(e) => setNewCustomer({ ...newCustomer, name: e.target.value })}
                      placeholder="Enter customer name"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label>{t('common.email')}</Label>
                    <Input
                      type="email"
                      value={newCustomer.email}
                      onChange={(e) => setNewCustomer({ ...newCustomer, email: e.target.value })}
                      placeholder="customer@example.com"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label>{t('common.address')}</Label>
                    <Input
                      value={newCustomer.address}
                      onChange={(e) => setNewCustomer({ ...newCustomer, address: e.target.value })}
                      placeholder="Customer address"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label>{t('vendors.vatNumber')}</Label>
                    <Input
                      value={newCustomer.vatNumber}
                      onChange={(e) => setNewCustomer({ ...newCustomer, vatNumber: e.target.value })}
                      placeholder="VAT registration number"
                    />
                  </div>
                </div>

                {/* Right Column */}
                <div className="space-y-4">
                  <div className="space-y-2">
                    <Label>{t('vendors.contactPerson')}</Label>
                    <Input
                      value={newCustomer.contactPerson}
                      onChange={(e) => setNewCustomer({ ...newCustomer, contactPerson: e.target.value })}
                      placeholder="Contact person name"
                    />
                  </div>

                  <div className="space-y-2">
                    <Label>{t('common.phone')}</Label>
                    <Input
                      value={newCustomer.phone}
                      onChange={(e) => setNewCustomer({ ...newCustomer, phone: e.target.value })}
                      placeholder="+966 XX XXX XXXX"
                    />
                  </div>
                </div>
              </div>

              {/* Buttons */}
              <div className="flex justify-end gap-2 pt-4">
                <Button variant="outline" onClick={() => setDialogOpen(false)}>
                  {t('common.cancel')}
                </Button>
                <Button 
                  onClick={handleCreateCustomer}
                  className="bg-[#A5747C] hover:bg-[#8B6268]"
                >
                  {t('customers.addCustomer')}
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      <div className="relative">
        <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
        <Input
          placeholder={t('customers.searchPlaceholder')}
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="pl-10"
        />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {isLoading && Array.from({ length: 6 }).map((_, i) => (
          <Card key={i}>
            <CardContent className="p-6">
              <div className="flex items-start gap-4 mb-4">
                <Skeleton className="w-12 h-12 rounded-full" />
                <div className="flex-1 space-y-2">
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-3 w-20" />
                </div>
              </div>
              <div className="space-y-2">
                <Skeleton className="h-3 w-full" />
                <Skeleton className="h-3 w-3/4" />
                <Skeleton className="h-3 w-1/2" />
              </div>
            </CardContent>
          </Card>
        ))}
        {!isLoading && filteredCustomers.map((customer) => {
          const customerProjects = projects.filter(p => p.customerId === customer.id);
          return (
            <Card 
              key={customer.id} 
              className="cursor-pointer hover:shadow-lg transition-shadow"
              onClick={() => navigate(`/customers/${customer.id}`)}
            >
              <CardContent className="p-6">
                <div className="flex items-start gap-4 mb-4">
                  <div className="w-12 h-12 bg-[#7A1516] text-white rounded-full flex items-center justify-center font-bold">
                    {getInitials(customer.name)}
                  </div>
                  <div className="flex-1">
                    <h3 className="font-semibold text-lg">{customer.name}</h3>
                    <p className="text-sm text-blue-600 font-mono">{customer.code}</p>
                    <p className="text-sm text-gray-500 mt-1">{customerProjects.length} project(s)</p>
                  </div>
                </div>

                <div className="space-y-2 text-sm">
                  <div>
                    <span className="text-gray-500">{t('common.contact')}:</span>
                    <span className="ml-2 font-medium">{customer.contactPerson || 'N/A'}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('common.email')}:</span>
                    <span className="ml-2 font-medium">{customer.email}</span>
                  </div>
                  <div>
                    <span className="text-gray-500">{t('common.phone')}:</span>
                    <span className="ml-2 font-medium">{customer.phone}</span>
                  </div>
                  {customer.vatNumber && (
                    <div>
                      <span className="text-gray-500">VAT:</span>
                      <span className="ml-2 font-medium">{customer.vatNumber}</span>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {!isLoading && filteredCustomers.length === 0 && (
        <div className="text-center py-12">
          <UserCircle className="w-12 h-12 text-gray-300 mx-auto mb-4" />
          <p className="text-gray-500">{t('customers.noCustomersFound')}</p>
        </div>
      )}
    </div>
  );
}