import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { toast } from 'sonner';
import { useLanguage } from '../contexts/LanguageContext';
import { useAuth } from '../contexts/AuthContext';
import { usePermissionsMatrix } from '../contexts/PermissionsMatrixContext';
import { dataStore, Project, ProjectStatus } from '../data/store';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '../components/ui/dialog';
import { Label } from '../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/ui/select';
import { Textarea } from '../components/ui/textarea';
import { Plus, Search, Filter, FolderKanban, ChevronDown, UserPlus, MoreVertical, Archive, ArchiveRestore, Trash2 } from 'lucide-react';
import { previewNextNumber } from '../utils/numberGenerator';
import { CustomerSelector } from '../components/CustomerSelector';
import { StatusDropdown } from '../components/StatusDropdown';
import { Skeleton } from '../components/ui/skeleton';
import { AccessDenied } from '../components/AccessDenied';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '../components/ui/dropdown-menu';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '../components/ui/alert-dialog';

export function ProjectsPage() {
  const { t } = useLanguage();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { hasPermission } = usePermissionsMatrix();
  const canViewProjects = hasPermission('projects', 'view');
  const canViewAllProjects = hasPermission('projects', 'view_all');
  const canDeleteProject = hasPermission('projects', 'delete');
  const canArchiveProject = hasPermission('projects', 'archive');
  const canViewBudget = hasPermission('budget', 'view');
  const canViewPayments = hasPermission('payments', 'view');
  const [projects, setProjects] = useState<Project[]>([]);
  const [projectsWithCalculations, setProjectsWithCalculations] = useState<any[]>([]);
  const [customers, setCustomers] = useState<any[]>([]);
  const [availableManagers, setAvailableManagers] = useState<{ id: string; name: string }[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<ProjectStatus | 'all'>('all');
  const [showArchived, setShowArchived] = useState(false);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [deleteConfirmProject, setDeleteConfirmProject] = useState<{ id: string; name: string } | null>(null);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');
  const [isLoading, setIsLoading] = useState(true);

  const loadProjectsWithCalcs = async () => {
    const [projectsData, customersData] = await Promise.all([
      dataStore.getProjects(),
      dataStore.getCustomers(),
    ]);
    setProjects(projectsData);
    setCustomers(customersData);
    // Show project cards immediately with base data, then update with calcs
    setProjectsWithCalculations(projectsData);
    setIsLoading(false);

    // Only fetch budget/payments when user has permission (avoids 403 for Employee)
    const withCalcs = await Promise.all(projectsData.map(async (project) => {
      if (canViewBudget && canViewPayments) {
        const [budgetItems, payments] = await Promise.all([
          dataStore.getBudgetItems(project.id),
          dataStore.getPayments(project.id),
        ]);
        const totalBudgeted = budgetItems.reduce((sum, item) => sum + item.budgeted, 0);
        const paidPayments = payments.filter((p: any) => p.type === 'payment' && (p.status === 'approved' || p.status === 'paid'));
        const totalSpent = paidPayments.reduce((sum: number, p: any) => sum + (p.subtotal || p.amount), 0);
        return {
          ...project,
          budget: totalBudgeted > 0 ? totalBudgeted : project.budget,
          spent: totalSpent,
        };
      }
      return {
        ...project,
        budget: project.budget ?? 0,
        spent: 0,
      };
    }));
    setProjectsWithCalculations(withCalcs);
  };

  // Load projects, customers, and PM users on mount
  useEffect(() => {
    loadProjectsWithCalcs();
  }, []);

  useEffect(() => {
    if (dialogOpen) {
      dataStore.getUsers().then((users) => {
        const managers = users
          .filter((u) => u.role === 'project_manager' || u.role === 'admin')
          .map((u) => ({ id: u.id, name: u.name }));
        setAvailableManagers(managers);
      });
    }
  }, [dialogOpen]);

  // Generate project code when dialog opens
  useEffect(() => {
    if (dialogOpen) {
      previewNextNumber('project').then(setAutoGeneratedCode);
    }
  }, [dialogOpen]);

  // When View All Projects is OFF: show projects where user is assigned as manager OR is a team member
  const isAssignedToProject = (p: Project) => {
    if (!user?.id) return false;
    if (p.assignedManagerId === user.id) return true;
    return (p.teamMembers || []).some((m: { userId?: string }) => m.userId === user.id);
  };
  const scopeProjects = canViewAllProjects
    ? projectsWithCalculations
    : projectsWithCalculations.filter((p: Project) => isAssignedToProject(p));

  const projectsExcludingArchived = showArchived ? scopeProjects : scopeProjects.filter((p: any) => !p.archived);

  const filteredProjects = projectsExcludingArchived.filter((project) => {
    const matchesSearch = project.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         project.code.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || project.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const handleArchive = async (projectId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await dataStore.updateProject(projectId, { archived: true });
      toast.success('Project archived');
      await loadProjectsWithCalcs();
    } catch (err: any) {
      toast.error(err.message || 'Failed to archive project');
    }
  };

  const handleUnarchive = async (projectId: string, e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await dataStore.updateProject(projectId, { archived: false });
      toast.success('Project unarchived');
      await loadProjectsWithCalcs();
    } catch (err: any) {
      toast.error(err.message || 'Failed to unarchive project');
    }
  };

  const handleDelete = async (projectId: string) => {
    try {
      await dataStore.deleteProject(projectId);
      toast.success('Project deleted');
      setDeleteConfirmProject(null);
      await loadProjectsWithCalcs();
    } catch (err: any) {
      toast.error(err.message || 'Failed to delete project');
    }
  };

  const handleCreateProject = async () => {
    if (!newProject.assignedManagerId) {
      toast.error(t('projects.managerRequiredError'));
      return;
    }
    await dataStore.addProject({
      ...newProject,
      assignedManagerId: newProject.assignedManagerId,
      assignedManagerName: newProject.assignedManagerName,
      teamMembers: [],
      spent: 0,
    });

    // Reload projects, customers, and recalculate budgets/spent
    await loadProjectsWithCalcs();

    setDialogOpen(false);
    setNewProject({
      name: '',
      status: 'planning',
      customerId: '',
      assignedManagerId: '',
      assignedManagerName: '',
      description: '',
      location: '',
      budget: 0,
      startDate: '',
      endDate: '',
      contractValue: 0,
      vatStatus: 'not_applicable' as 'not_applicable' | 'inclusive' | 'exclusive',
      contractDocument: '',
      contractDocumentName: '',
      contractLink: '',
    });
  };

  const getStatusColor = (status: ProjectStatus) => {
    switch (status) {
      case 'active': return 'bg-green-100 text-green-700 hover:bg-green-200';
      case 'planning': return 'bg-yellow-100 text-yellow-700 hover:bg-yellow-200';
      case 'on_hold': return 'bg-red-100 text-red-700 hover:bg-red-200';
      case 'completed': return 'bg-blue-100 text-blue-700 hover:bg-blue-200';
    }
  };

  const formatCurrency = (amount: number) => {
    return `${amount.toLocaleString('en-SA')} SAR`;
  };

  const [newProject, setNewProject] = useState({
    name: '',
    status: 'planning' as ProjectStatus,
    customerId: '',
    assignedManagerId: '',
    assignedManagerName: '',
    description: '',
    location: '',
    budget: 0,
    startDate: '',
    endDate: '',
    contractValue: 0,
    vatStatus: 'not_applicable' as 'not_applicable' | 'inclusive' | 'exclusive',
    contractDocument: '',
    contractDocumentName: '',
    contractLink: '',
  });

  const handleStatusChange = async (projectId: string, newStatus: ProjectStatus) => {
    await dataStore.updateProject(projectId, { status: newStatus });
    await loadProjectsWithCalcs();
  };

  // Calculate VAT breakdown
  const calculateVATBreakdown = () => {
    const contractValue = newProject.contractValue || 0;
    const VAT_RATE = 0.15;

    if (newProject.vatStatus === 'not_applicable') {
      return {
        displayText: `Total: ${contractValue.toLocaleString('en-SA')} SAR`,
        subtotal: contractValue,
        vatAmount: 0,
        total: contractValue,
      };
    } else if (newProject.vatStatus === 'inclusive') {
      const valueWithoutVAT = contractValue / 1.15;
      const vatAmount = contractValue - valueWithoutVAT;
      return {
        displayText: `${valueWithoutVAT.toFixed(2)} SAR (without VAT)`,
        subtotal: valueWithoutVAT,
        vatAmount: vatAmount,
        total: contractValue,
      };
    } else { // exclusive
      const vatAmount = contractValue * VAT_RATE;
      const total = contractValue + vatAmount;
      return {
        displayText: `${contractValue.toLocaleString('en-SA')} SAR + ${vatAmount.toLocaleString('en-SA')} SAR VAT`,
        subtotal: contractValue,
        vatAmount: vatAmount,
        total: total,
      };
    }
  };

  const vatBreakdown = calculateVATBreakdown();

  if (!canViewProjects) {
    return <AccessDenied message={t('common.accessDenied')} />;
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold">{t('projects.title')}</h1>
          <p className="text-gray-500 mt-1">{t('projects.subtitle')}</p>
        </div>

        {hasPermission('projects', 'create') && (
          <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
            <DialogTrigger asChild>
              <Button className="bg-[#7A1516] hover:bg-[#5A1012]">
                <Plus className="w-4 h-4 mr-2" />
                {t('projects.newProject')}
              </Button>
            </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>{t('projects.newProject')}</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>{t('projects.projectName')}</Label>
                  <Input
                    value={newProject.name}
                    onChange={(e) => setNewProject({ ...newProject, name: e.target.value })}
                    placeholder="Enter project name"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="flex items-center gap-2">
                    Project Code
                    <span className="text-xs text-blue-600 font-normal">(Auto-generated)</span>
                  </Label>
                  <Input
                    value={autoGeneratedCode}
                    readOnly
                    className="bg-blue-50 border-blue-200 text-blue-900 font-mono"
                    placeholder="Auto-generated code"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>{t('projects.assignManager')} *</Label>
                  <Select
                    value={newProject.assignedManagerId || ''}
                    onValueChange={(value) => {
                      const manager = availableManagers.find((m) => m.id === value);
                      setNewProject({
                        ...newProject,
                        assignedManagerId: value,
                        assignedManagerName: manager?.name ?? '',
                      });
                    }}
                    required
                  >
                    <SelectTrigger>
                      <SelectValue placeholder={t('projects.selectManager')} />
                    </SelectTrigger>
                    <SelectContent>
                      {availableManagers.map((m) => (
                        <SelectItem key={m.id} value={m.id}>
                          {m.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>{t('common.status')}</Label>
                  <Select value={newProject.status} onValueChange={(value) => setNewProject({ ...newProject, status: value as ProjectStatus })}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="planning">Planning</SelectItem>
                      <SelectItem value="active">Active</SelectItem>
                      <SelectItem value="on_hold">On Hold</SelectItem>
                      <SelectItem value="completed">Completed</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2 col-span-2">
                  <Label>{t('projects.customer')}</Label>
                  <CustomerSelector
                    value={newProject.customerId}
                    onChange={(value) => setNewProject({ ...newProject, customerId: value })}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label>Location</Label>
                <Input
                  value={newProject.location}
                  onChange={(e) => setNewProject({ ...newProject, location: e.target.value })}
                  placeholder="Project location"
                />
              </div>

              <div className="space-y-2">
                <Label>Description</Label>
                <Textarea
                  value={newProject.description}
                  onChange={(e) => setNewProject({ ...newProject, description: e.target.value })}
                  placeholder="Project description"
                  rows={3}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Start Date</Label>
                  <Input
                    type="date"
                    value={newProject.startDate}
                    onChange={(e) => setNewProject({ ...newProject, startDate: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label>End Date</Label>
                  <Input
                    type="date"
                    value={newProject.endDate}
                    onChange={(e) => setNewProject({ ...newProject, endDate: e.target.value })}
                  />
                </div>
              </div>

              {/* Contract Value Section */}
              <div className="border-t pt-4">
                <h3 className="font-semibold mb-4 text-[#7A1516]">Contract Details</h3>
                
                <div className="grid grid-cols-2 gap-4 mb-4">
                  <div className="space-y-2">
                    <Label>Contract Value (SAR)</Label>
                    <Input
                      type="number"
                      value={newProject.contractValue}
                      onChange={(e) => setNewProject({ ...newProject, contractValue: parseFloat(e.target.value) || 0 })}
                      placeholder="0"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label>VAT Status</Label>
                    <Select 
                      value={newProject.vatStatus} 
                      onValueChange={(value) => setNewProject({ ...newProject, vatStatus: value as 'not_applicable' | 'inclusive' | 'exclusive' })}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="not_applicable">Not Applicable</SelectItem>
                        <SelectItem value="inclusive">VAT Inclusive</SelectItem>
                        <SelectItem value="exclusive">VAT Exclusive</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="space-y-4">
                  <div className="space-y-2">
                    <Label>Upload Contract Document</Label>
                    <Input
                      type="file"
                      accept=".pdf,.doc,.docx"
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (!file) return;
                        if (file.size > 10 * 1024 * 1024) {
                          alert('File must be under 10MB');
                          return;
                        }
                        const reader = new FileReader();
                        reader.onload = (ev) => {
                          const base64 = ev.target?.result as string;
                          setNewProject(prev => ({ ...prev, contractDocument: base64, contractDocumentName: file.name }));
                        };
                        reader.readAsDataURL(file);
                      }}
                      className="cursor-pointer"
                    />
                    {newProject.contractDocumentName && (
                      <p className="text-xs text-green-600 font-medium">✓ {newProject.contractDocumentName} selected</p>
                    )}
                    <p className="text-xs text-gray-500">Upload PDF, DOC, or DOCX file (Max 10MB)</p>
                  </div>

                  <div className="relative flex items-center">
                    <div className="flex-grow border-t border-gray-300"></div>
                    <span className="flex-shrink mx-4 text-gray-400 text-sm">OR</span>
                    <div className="flex-grow border-t border-gray-300"></div>
                  </div>

                  <div className="space-y-2">
                    <Label>Cloud Storage Link</Label>
                    <Input
                      type="url"
                      value={newProject.contractLink}
                      onChange={(e) => setNewProject({ ...newProject, contractLink: e.target.value })}
                      placeholder="https://drive.google.com/... or https://onedrive.com/..."
                    />
                    <p className="text-xs text-gray-500">Link to Google Drive, OneDrive, Dropbox, etc.</p>
                  </div>
                </div>

                {/* VAT Breakdown Display */}
                {newProject.contractValue > 0 && (
                  <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 mt-4">
                    <h4 className="font-medium text-sm mb-3">Contract Value Breakdown</h4>
                    
                    {newProject.vatStatus === 'not_applicable' && (
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Total</span>
                          <span className="font-semibold">{newProject.contractValue.toLocaleString('en-SA')} SAR</span>
                        </div>
                      </div>
                    )}

                    {newProject.vatStatus === 'inclusive' && (
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Contract Value</span>
                          <span className="font-semibold">{newProject.contractValue.toLocaleString('en-SA')} SAR</span>
                        </div>
                        <div className="flex justify-between text-sm border-t pt-2">
                          <span className="text-gray-600">Value Without VAT</span>
                          <span className="font-semibold text-green-600">{(newProject.contractValue / 1.15).toFixed(2)} SAR</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">VAT Amount (15%)</span>
                          <span className="font-semibold text-gray-500">{(newProject.contractValue - (newProject.contractValue / 1.15)).toFixed(2)} SAR</span>
                        </div>
                      </div>
                    )}

                    {newProject.vatStatus === 'exclusive' && (
                      <div className="space-y-2">
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">Contract Value</span>
                          <span className="font-semibold">{newProject.contractValue.toLocaleString('en-SA')} SAR</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span className="text-gray-600">VAT (15%)</span>
                          <span className="font-semibold text-gray-500">+ {(newProject.contractValue * 0.15).toLocaleString('en-SA')} SAR</span>
                        </div>
                        <div className="flex justify-between text-sm border-t pt-2">
                          <span className="text-gray-600">Total (Incl. VAT)</span>
                          <span className="font-semibold text-green-600">{(newProject.contractValue * 1.15).toLocaleString('en-SA')} SAR</span>
                        </div>
                      </div>
                    )}
                  </div>
                )}
              </div>

              <div className="flex justify-end gap-2 pt-4">
                <Button variant="outline" onClick={() => setDialogOpen(false)}>
                  {t('common.cancel')}
                </Button>
                <Button onClick={handleCreateProject} className="bg-[#7A1516] hover:bg-[#5A1012]">
                  {t('common.save')}
                </Button>
              </div>
            </div>
          </DialogContent>
          </Dialog>
        )}
      </div>

      {/* Filters */}
      <div className="flex flex-col md:flex-row gap-4">
        <div className="flex-1 relative">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
          <Input
            placeholder={t('common.search')}
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10"
          />
        </div>
        <Select value={statusFilter} onValueChange={(value) => setStatusFilter(value as ProjectStatus | 'all')}>
          <SelectTrigger className="w-full md:w-48">
            <Filter className="w-4 h-4 mr-2" />
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">{t('projects.allStatus')}</SelectItem>
            <SelectItem value="planning">Planning</SelectItem>
            <SelectItem value="active">Active</SelectItem>
            <SelectItem value="on_hold">On Hold</SelectItem>
            <SelectItem value="completed">Completed</SelectItem>
          </SelectContent>
        </Select>
        {canArchiveProject && (
          <label className="flex items-center gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={showArchived}
              onChange={(e) => setShowArchived(e.target.checked)}
              className="rounded border-gray-300"
            />
            <span className="text-sm text-gray-600">Show archived</span>
          </label>
        )}
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {(['planning', 'active', 'on_hold', 'completed'] as ProjectStatus[]).map(status => {
          const count = projectsExcludingArchived.filter(p => p.status === status).length;
          return (
            <Card key={status} className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => setStatusFilter(status)}>
              <CardContent className="p-4">
                <div className="text-2xl font-bold">{count}</div>
                <div className="text-sm text-gray-500 capitalize">{status.replace('_', ' ')}</div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Projects Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {isLoading && Array.from({ length: 6 }).map((_, i) => (
          <Card key={i}>
            <CardHeader className="pb-3">
              <div className="flex items-center gap-3">
                <Skeleton className="w-12 h-12 rounded-lg" />
                <div className="space-y-2">
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-3 w-20" />
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <Skeleton className="h-2 w-full rounded-full" />
                <Skeleton className="h-4 w-3/4" />
                <Skeleton className="h-4 w-1/2" />
              </div>
            </CardContent>
          </Card>
        ))}
        {!isLoading && filteredProjects.map((project) => {
          const customer = customers.find(c => c.id === project.customerId);
          const progress = project.budget && project.budget > 0 ? (project.spent / project.budget) * 100 : 0;
          const isArchived = !!project.archived;

          return (
            <Card key={project.id} className="cursor-pointer hover:shadow-lg transition-shadow" onClick={() => navigate(`/projects/${project.id}`)}>
              <CardHeader className="pb-3">
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 bg-[#7A1516] rounded-lg flex items-center justify-center text-white font-bold text-lg">
                      {project.name.charAt(0)}
                    </div>
                    <div>
                      <CardTitle className="text-lg mb-1">{project.name}</CardTitle>
                      <p className="text-sm text-gray-500">{project.code}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-1" onClick={(e) => e.stopPropagation()}>
                    <StatusDropdown
                      currentStatus={project.status}
                      onStatusChange={(newStatus) => handleStatusChange(project.id, newStatus)}
                    />
                    {(canArchiveProject || canDeleteProject) && (
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon" className="h-8 w-8">
                            <MoreVertical className="w-4 h-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          {canArchiveProject && !isArchived && project.status === 'completed' && (
                            <DropdownMenuItem onClick={(e) => handleArchive(project.id, e as unknown as React.MouseEvent)}>
                              <Archive className="w-4 h-4 mr-2" />
                              Archive
                            </DropdownMenuItem>
                          )}
                          {canArchiveProject && isArchived && (
                            <DropdownMenuItem onClick={(e) => handleUnarchive(project.id, e as unknown as React.MouseEvent)}>
                              <ArchiveRestore className="w-4 h-4 mr-2" />
                              Unarchive
                            </DropdownMenuItem>
                          )}
                          {canDeleteProject && (
                            <DropdownMenuItem
                              variant="destructive"
                              onClick={(e) => { e.preventDefault(); setDeleteConfirmProject({ id: project.id, name: project.name }); }}
                            >
                              <Trash2 className="w-4 h-4 mr-2" />
                              Delete
                            </DropdownMenuItem>
                          )}
                        </DropdownMenuContent>
                      </DropdownMenu>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div>
                    <div className="flex items-center justify-between text-sm mb-1">
                      <span className="text-gray-500">{t('projects.progress')}</span>
                      <span className="font-semibold">{progress.toFixed(1)}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div
                        className="bg-[#7A1516] h-2 rounded-full transition-all"
                        style={{ width: `${Math.min(progress, 100)}%` }}
                      />
                    </div>
                  </div>

                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-500">{t('projects.budget')}</span>
                    <span className="font-semibold">{formatCurrency(project.budget)}</span>
                  </div>

                  <div className="flex items-center justify-between text-sm">
                    <span className="text-gray-500">{t('projects.spent')}</span>
                    <span className="font-semibold">{formatCurrency(project.spent)}</span>
                  </div>

                  <div className="pt-3 border-t">
                    <div className="text-sm text-gray-500">{t('projects.customer')}</div>
                    <div className="font-medium">{customer?.name || 'N/A'}</div>
                  </div>

                  {project.location && (
                    <div className="text-sm text-gray-500">{project.location}</div>
                  )}
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {!isLoading && filteredProjects.length === 0 && (
        <div className="text-center py-12">
          <FolderKanban className="w-12 h-12 text-gray-300 mx-auto mb-4" />
          <p className="text-gray-500">No projects found</p>
        </div>
      )}

      <AlertDialog open={!!deleteConfirmProject} onOpenChange={(open) => !open && setDeleteConfirmProject(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Project</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete &quot;{deleteConfirmProject?.name}&quot;? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              className="bg-red-600 hover:bg-red-700"
              onClick={() => deleteConfirmProject && handleDelete(deleteConfirmProject.id)}
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}