-- Seed default RBAC permissions for built-in roles (admin, project_manager, finance, employee)
-- Based on Projex/Core Code spec: admin=full, project_manager=projects/tasks/budget/POs, finance=financial, employee=limited
-- Only runs when role_permissions is empty

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM role_permissions) = 0 THEN
    -- Admin: full access to all
    INSERT INTO role_permissions (id, role_id, module, action, allowed) VALUES
      (gen_random_uuid()::text, 'admin', 'dashboard', 'view', true),
      (gen_random_uuid()::text, 'admin', 'dashboard', 'view_all_projects', true),
      (gen_random_uuid()::text, 'admin', 'dashboard', 'view_financial', true),
      (gen_random_uuid()::text, 'admin', 'projects', 'view', true),
      (gen_random_uuid()::text, 'admin', 'projects', 'view_all', true),
      (gen_random_uuid()::text, 'admin', 'projects', 'create', true),
      (gen_random_uuid()::text, 'admin', 'projects', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'projects', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'projects', 'archive', true),
      (gen_random_uuid()::text, 'admin', 'tasks', 'view', true),
      (gen_random_uuid()::text, 'admin', 'tasks', 'view_all', true),
      (gen_random_uuid()::text, 'admin', 'tasks', 'create', true),
      (gen_random_uuid()::text, 'admin', 'tasks', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'tasks', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'tasks', 'assign', true),
      (gen_random_uuid()::text, 'admin', 'tasks', 'update_status', true),
      (gen_random_uuid()::text, 'admin', 'budget', 'view', true),
      (gen_random_uuid()::text, 'admin', 'budget', 'create', true),
      (gen_random_uuid()::text, 'admin', 'budget', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'budget', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'budget', 'manage_categories', true),
      (gen_random_uuid()::text, 'admin', 'purchase_orders', 'view', true),
      (gen_random_uuid()::text, 'admin', 'purchase_orders', 'create', true),
      (gen_random_uuid()::text, 'admin', 'purchase_orders', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'purchase_orders', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'purchase_orders', 'submit', true),
      (gen_random_uuid()::text, 'admin', 'purchase_orders', 'approve', true),
      (gen_random_uuid()::text, 'admin', 'purchase_orders', 'reject', true),
      (gen_random_uuid()::text, 'admin', 'vendor_invoices', 'view', true),
      (gen_random_uuid()::text, 'admin', 'vendor_invoices', 'create', true),
      (gen_random_uuid()::text, 'admin', 'vendor_invoices', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'vendor_invoices', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'vendor_invoices', 'approve', true),
      (gen_random_uuid()::text, 'admin', 'vendor_invoices', 'reject', true),
      (gen_random_uuid()::text, 'admin', 'payments', 'view', true),
      (gen_random_uuid()::text, 'admin', 'payments', 'create', true),
      (gen_random_uuid()::text, 'admin', 'payments', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'payments', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'payments', 'approve_level1', true),
      (gen_random_uuid()::text, 'admin', 'payments', 'approve_level2', true),
      (gen_random_uuid()::text, 'admin', 'payments', 'process', true),
      (gen_random_uuid()::text, 'admin', 'customer_invoices', 'view', true),
      (gen_random_uuid()::text, 'admin', 'customer_invoices', 'create', true),
      (gen_random_uuid()::text, 'admin', 'customer_invoices', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'customer_invoices', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'customer_invoices', 'approve', true),
      (gen_random_uuid()::text, 'admin', 'customer_invoices', 'issue', true),
      (gen_random_uuid()::text, 'admin', 'vendors', 'view', true),
      (gen_random_uuid()::text, 'admin', 'vendors', 'create', true),
      (gen_random_uuid()::text, 'admin', 'vendors', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'vendors', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'customers', 'view', true),
      (gen_random_uuid()::text, 'admin', 'customers', 'create', true),
      (gen_random_uuid()::text, 'admin', 'customers', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'customers', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'employees', 'view', true),
      (gen_random_uuid()::text, 'admin', 'employees', 'view_all', true),
      (gen_random_uuid()::text, 'admin', 'employees', 'create', true),
      (gen_random_uuid()::text, 'admin', 'employees', 'edit', true),
      (gen_random_uuid()::text, 'admin', 'employees', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'documents', 'view', true),
      (gen_random_uuid()::text, 'admin', 'documents', 'upload', true),
      (gen_random_uuid()::text, 'admin', 'documents', 'download', true),
      (gen_random_uuid()::text, 'admin', 'documents', 'delete', true),
      (gen_random_uuid()::text, 'admin', 'documents', 'manage_permissions', true),
      (gen_random_uuid()::text, 'admin', 'reports', 'view', true),
      (gen_random_uuid()::text, 'admin', 'reports', 'view_financial', true),
      (gen_random_uuid()::text, 'admin', 'reports', 'export', true),
      (gen_random_uuid()::text, 'admin', 'settings', 'view', true),
      (gen_random_uuid()::text, 'admin', 'settings', 'edit_company', true),
      (gen_random_uuid()::text, 'admin', 'settings', 'edit_system', true),
      (gen_random_uuid()::text, 'admin', 'settings', 'manage_users', true),
      (gen_random_uuid()::text, 'admin', 'settings', 'manage_roles', true);

    -- Project Manager: projects, tasks, budget, POs, documents (most actions except delete where noted)
    INSERT INTO role_permissions (id, role_id, module, action, allowed) VALUES
      (gen_random_uuid()::text, 'project_manager', 'dashboard', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'dashboard', 'view_all_projects', true),
      (gen_random_uuid()::text, 'project_manager', 'dashboard', 'view_financial', true),
      (gen_random_uuid()::text, 'project_manager', 'projects', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'projects', 'view_all', true),
      (gen_random_uuid()::text, 'project_manager', 'projects', 'create', true),
      (gen_random_uuid()::text, 'project_manager', 'projects', 'edit', true),
      (gen_random_uuid()::text, 'project_manager', 'projects', 'archive', true),
      (gen_random_uuid()::text, 'project_manager', 'tasks', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'tasks', 'view_all', true),
      (gen_random_uuid()::text, 'project_manager', 'tasks', 'create', true),
      (gen_random_uuid()::text, 'project_manager', 'tasks', 'edit', true),
      (gen_random_uuid()::text, 'project_manager', 'tasks', 'assign', true),
      (gen_random_uuid()::text, 'project_manager', 'tasks', 'update_status', true),
      (gen_random_uuid()::text, 'project_manager', 'budget', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'budget', 'create', true),
      (gen_random_uuid()::text, 'project_manager', 'budget', 'edit', true),
      (gen_random_uuid()::text, 'project_manager', 'purchase_orders', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'purchase_orders', 'create', true),
      (gen_random_uuid()::text, 'project_manager', 'purchase_orders', 'edit', true),
      (gen_random_uuid()::text, 'project_manager', 'purchase_orders', 'submit', true),
      (gen_random_uuid()::text, 'project_manager', 'purchase_orders', 'approve', true),
      (gen_random_uuid()::text, 'project_manager', 'purchase_orders', 'reject', true),
      (gen_random_uuid()::text, 'project_manager', 'documents', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'documents', 'upload', true),
      (gen_random_uuid()::text, 'project_manager', 'documents', 'download', true),
      (gen_random_uuid()::text, 'project_manager', 'vendors', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'customers', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'employees', 'view', true),
      (gen_random_uuid()::text, 'project_manager', 'settings', 'view', true);

    -- Finance: financial modules + reports
    INSERT INTO role_permissions (id, role_id, module, action, allowed) VALUES
      (gen_random_uuid()::text, 'finance', 'dashboard', 'view', true),
      (gen_random_uuid()::text, 'finance', 'dashboard', 'view_all_projects', true),
      (gen_random_uuid()::text, 'finance', 'dashboard', 'view_financial', true),
      (gen_random_uuid()::text, 'finance', 'purchase_orders', 'view', true),
      (gen_random_uuid()::text, 'finance', 'purchase_orders', 'create', true),
      (gen_random_uuid()::text, 'finance', 'purchase_orders', 'edit', true),
      (gen_random_uuid()::text, 'finance', 'purchase_orders', 'submit', true),
      (gen_random_uuid()::text, 'finance', 'purchase_orders', 'approve', true),
      (gen_random_uuid()::text, 'finance', 'purchase_orders', 'reject', true),
      (gen_random_uuid()::text, 'finance', 'vendor_invoices', 'view', true),
      (gen_random_uuid()::text, 'finance', 'vendor_invoices', 'create', true),
      (gen_random_uuid()::text, 'finance', 'vendor_invoices', 'edit', true),
      (gen_random_uuid()::text, 'finance', 'vendor_invoices', 'delete', true),
      (gen_random_uuid()::text, 'finance', 'vendor_invoices', 'approve', true),
      (gen_random_uuid()::text, 'finance', 'vendor_invoices', 'reject', true),
      (gen_random_uuid()::text, 'finance', 'payments', 'view', true),
      (gen_random_uuid()::text, 'finance', 'payments', 'create', true),
      (gen_random_uuid()::text, 'finance', 'payments', 'edit', true),
      (gen_random_uuid()::text, 'finance', 'payments', 'approve_level1', true),
      (gen_random_uuid()::text, 'finance', 'payments', 'approve_level2', true),
      (gen_random_uuid()::text, 'finance', 'payments', 'process', true),
      (gen_random_uuid()::text, 'finance', 'customer_invoices', 'view', true),
      (gen_random_uuid()::text, 'finance', 'customer_invoices', 'create', true),
      (gen_random_uuid()::text, 'finance', 'customer_invoices', 'edit', true),
      (gen_random_uuid()::text, 'finance', 'customer_invoices', 'delete', true),
      (gen_random_uuid()::text, 'finance', 'customer_invoices', 'approve', true),
      (gen_random_uuid()::text, 'finance', 'customer_invoices', 'issue', true),
      (gen_random_uuid()::text, 'finance', 'reports', 'view', true),
      (gen_random_uuid()::text, 'finance', 'reports', 'view_financial', true),
      (gen_random_uuid()::text, 'finance', 'reports', 'export', true),
      (gen_random_uuid()::text, 'finance', 'projects', 'view', true),
      (gen_random_uuid()::text, 'finance', 'projects', 'view_all', true),
      (gen_random_uuid()::text, 'finance', 'vendors', 'view', true),
      (gen_random_uuid()::text, 'finance', 'customers', 'view', true),
      (gen_random_uuid()::text, 'finance', 'settings', 'view', true);

    -- Employee: limited - view dashboard, projects, documents, tasks (view + update_status)
    INSERT INTO role_permissions (id, role_id, module, action, allowed) VALUES
      (gen_random_uuid()::text, 'employee', 'dashboard', 'view', true),
      (gen_random_uuid()::text, 'employee', 'projects', 'view', true),
      (gen_random_uuid()::text, 'employee', 'projects', 'view_all', true),
      (gen_random_uuid()::text, 'employee', 'documents', 'view', true),
      (gen_random_uuid()::text, 'employee', 'documents', 'download', true),
      (gen_random_uuid()::text, 'employee', 'tasks', 'view', true),
      (gen_random_uuid()::text, 'employee', 'tasks', 'view_all', true),
      (gen_random_uuid()::text, 'employee', 'tasks', 'update_status', true);
  END IF;
END $$;
